###################################################################
#
# Configuration file for the SvxReflector SvxLink conference node
#
###################################################################

[GLOBAL]
TIMESTAMP_FORMAT="%c"
LISTEN_PORT=5300
TG_FOR_V1_CLIENTS=999
HTTP_SRV_PORT=8080
COMMAND_PTY=/dev/shm/reflector_ctrl
CERT_CA_HOOK=/usr/local/share/svxlink/ca-hook.py

[ROOT_CA]

[ISSUING_CA]

[SERVER_CERT]
COMMON_NAME=PU1DES-REFLECTOR
ORG_UNIT=PU1DES
COUNTRY=BR
[USERS]
PP1ABB=PP1ABB
PP1DGR-R=PP1DGR-R
PP1ICH-R=PP1ICH-R

[PASSWORDS]
PP1ABB=12345
PP1DGR-R=de7832ten
PP1ICH-R=de7832ten

[TG#999]
